<html>
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>        

        <style>
            h1 {
                text-align: center;
            }
        </style>

        <script type='text/javascript'>
            function errorMessage(message) {
                $('#error-dialog .modal-body').html(message);
                $('#error-dialog').modal('show');
            }

            function successMessage(message) {
                $('#message-dialog .modal-body').html(message);
                $('#message-dialog').modal('show');
            }

            $(document).ready(function() {
                $('#checkin-btn').on('click', function() {
                    var plate = $('#checkin_license_plate').val();
                    var type = $('#type').val();

                    $.ajax({
                        url: '/api/parking/park',
                        method: 'POST',
                        data: { plate: plate, type: type },
                        success: function(response) {
                            var json = JSON.parse(response);

                            if (json.hasOwnProperty('error')) {
                                errorMessage(json.error.replace("\n", "<br/>"));
                            } else {
                                successMessage("Car has checked in at " + json.check_in + " in spot: " + json.spot);
                            }
                        }
                    });
                });

                $('#checkout-btn').on('click', function() {
                    var plate = $('#checkout_license_plate').val();

                    $.ajax({
                        url: '/api/parking/park',
                        method: 'PUT',
                        data: { plate: plate },
                        success: function(response) {
                            var json = JSON.parse(response);

                            if (json.hasOwnProperty('error')) {
                                errorMessage(json.error.replace("\n", "<br/>"));
                            } else {
                                successMessage("Car has checked out at " + json.check_out + ". Duration: " + json.duration + " minute(s) for $" + json.amount);
                            }
                        }
                    });
                });
            });
        </script>
    </head>

    <body>
        <div id="error-dialog" class="modal fade">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Error</h4>
                    </div>
                    <div class="modal-body">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>

        <div id="message-dialog" class="modal fade">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Success</h4>
                    </div>
                    <div class="modal-body">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" data-dismiss="modal">OK</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="jumbotron">
            <div class='row'>
                <div class='col-sm-12'>
                    <h1>Parking App</h1>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-3"></div>
                <div class="col-sm-6">
                    <h2>Check In</h2>

                    <form class="inline-form">
                        <div class="form-group">
                            <label for="license_plate">License Plate</label>
                            <input type="text" id='checkin_license_plate' class="form-control" default="License Plate"/>
                        </div>
                        <div class="form-group">
                            <label for='type'>Car Type</label>
                            <select id='type' class="form-control">
                                <option value='small'>Small</option>
                                <option value='medium'>Medium</option>
                                <option value='xtra-large'>Extra Large</option>
                            </select>                            
                        </div>
                        <div class="form-group">
                            <button type="button" id='checkin-btn' class="btn btn-primary">Check In</button>
                        </div>
                    </form>
                </div>
                <div class="col-sm-3"></div>
            </div>

            <div class="row">
                <div class="col-sm-3"></div>
                <div class="col-sm-6">
                    <h2>Check Out</h2>

                    <form class="inline-form">
                        <div class="form-group">
                            <label for="license_plate">License Plate</label>
                            <input type="text" id='checkout_license_plate' class="form-control" default="License Plate"/>
                        </div>
                        <div class="form-group">
                            <button type="button" id='checkout-btn' class="btn btn-primary">Check Out</button>
                        </div>
                    </form>
                </div>
                <div class="col-sm-3"></div>
            </div>
        </div>
    </body>
</html>

