<html>
    <head>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>        

        <style>
            h1 {
                text-align: center;
            }
        </style>

        <script type='text/javascript' src="scripts/app.js"></script>
    </head>

    <body>
        <div id="error-dialog" class="modal fade">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Error</h4>
                    </div>
                    <div class="modal-body">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>

        <div id="message-dialog" class="modal fade">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Success</h4>
                    </div>
                    <div class="modal-body">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-success" data-dismiss="modal">OK</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="jumbotron">
            <div class='row'>
                <div class='col-sm-12'>
                    <h1>Parking App</h1>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-3"></div>
                <div class="col-sm-6">
                    <h2>Check In</h2>

                    <form class="inline-form">
                        <div class="form-group">
                            <label for="checkin_parking_lot">Parking Lot</label>
                            <select id="checkin_parking_lot" class="form-control">
                                <?php
                                    foreach ($parkingLots as $parkingLot) {
                                        echo "<option value='{$parkingLot->id}'>{$parkingLot->name}</option>";
                                    }
                                ?>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="license_plate">License Plate</label>
                            <input type="text" id='checkin_license_plate' class="form-control" default="License Plate"/>
                        </div>
                        <div class="form-group">
                            <label for='type'>Car Type</label>
                            <select id='type' class="form-control">
                                <?php
                                    foreach ($types as $type) {
                                        echo "<option value='$type'>" . ucwords(str_replace('_', ' ', $type)) . "</option>";
                                    }
                                ?>
                            </select>                            
                        </div>
                        <div class="form-group">
                            <button type="button" id='checkin-btn' class="btn btn-primary">Check In</button>
                        </div>
                    </form>
                </div>
                <div class="col-sm-3"></div>
            </div>

            <div class="row">
                <div class="col-sm-3"></div>
                <div class="col-sm-6">
                    <h2>Check Out</h2>

                    <form class="inline-form">
                        <div class="form-group">
                            <label for="checkout_parking_lot">Parking Lot</label>
                            <select id="checkout_parking_lot" class="form-control">
                                <?php
                                    foreach ($parkingLots as $parkingLot) {
                                        echo "<option value='{$parkingLot->id}'>{$parkingLot->name}</option>";
                                    }
                                ?>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="license_plate">License Plate</label>
                            <input type="text" id='checkout_license_plate' class="form-control" default="License Plate"/>
                        </div>
                        <div class="form-group">
                            <button type="button" id='checkout-btn' class="btn btn-primary">Check Out</button>
                        </div>
                    </form>
                </div>
                <div class="col-sm-3"></div>
            </div>
            <div class="row">
                <div class="col-sm-3"></div>
                <div class="col-sm-6">
                    <h2>Find Car</h2>

                    <form class="inline-form">
                        <div class="form-group">
                            <label for="license_plate">License Plate</label>
                            <input type="text" id='find_license_plate' class="form-control" default="License Plate"/>
                        </div>
                        <div class="form-group">
                            <button type="button" id='find-btn' class="btn btn-primary">Find Car</button>
                        </div>
                    </form>
                </div>
                <div class="col-sm-3"></div>
            </div>
        </div>
    </body>
</html>

